language: python
python:
        - "3.6"
install:
        - pip install pipenv
        - pipenv install
script:
        - cd heimdall
        - pipenv run coverage run -m unittest discover -s test/ -vv
